DECAY_RATE = 0.1
LEARNING_RATE = 0.2
SLIP_PROB = 0.1
GUESS_PROB = 0.2

DEFAULT_AVG_RESPONSE_TIME = 30.0
AVG_TIME_CONFIG = {
	"math.algebra.linear_equations": 45.0,
	"math.calculus.derivatives": 60.0,
}

MAX_QUESTION_HISTORY = 15
MAX_RECENT_CONCEPTS = 3

DEFAULT_TOPIC_CONCEPTS = {
	"math.algebra": ["linear_equations", "quadratic_equations"],
	"math.calculus": ["derivatives", "limits"],
}

WEAK_MASTERY_THRESHOLD = 0.5
STRONG_MASTERY_THRESHOLD = 0.8

NUM_QUESTIONS_MIN = 5
NUM_QUESTIONS_MAX = 20

RISK_DECAY_LAMBDA = 0.001

CONFIDENCE_SPEED_MIN = 0.5
CONFIDENCE_SPEED_MAX = 1.5
CONFIDENCE_EPSILON = 1e-5
CONFIDENCE_BASE_LR = 0.05
CONFIDENCE_ADAPTIVE_LR = 0.05

RISK_WEIGHT_MASTERY = -2.0
RISK_WEIGHT_CONFIDENCE = -1.5
RISK_WEIGHT_RECENCY = -1.0
RISK_WEIGHT_ACCURACY = -2.5
RISK_BIAS = 1.5
RISK_TOLERANCE = 1e-5
RISK_HIGH_THRESHOLD = 0.7
RISK_MEDIUM_THRESHOLD = 0.4

PASSWORD_MIN_LENGTH = 8
